### PR TITLE
refactor: deprecate some names

### PR DESCRIPTION
**Pull request by splincode**

### CODE REVIEW

**Comment by splincode** [comment]
@waterplea please, review me

**Review by waterplea — COMMENTED** [review]
1. I don't think we should prefix the helpers, just the tokens
2. We should add `use {@link XXX} ` to deprecation comments, otherwise people will think something is just going away

**Comment by splincode** [comment]
fixed

**Review by waterplea — APPROVED** [review]
Should we, maybe, drop token descriptions to save bundle size? Or maybe only add them in dev mode like Angular does.

**Comment by splincode** [comment]
fixed

**Pull request merged**
